name: test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [stable, 1.63, nightly]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install dependencies
        run: sudo apt-get install libwebp-dev libwebpdemux2 libwebpmux3
        if: runner.os == 'linux'

      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{matrix.rust}}
          components: rustfmt, clippy

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Run fmt
        run: cargo fmt --check

      - name: Run clippy
        run: cargo clippy

      - name: Run tests
        run: cargo test --verbose

      - name: Run tests with image feature
        run: cargo test --verbose --features image
